baseURL = 'https://j-maas.github.io/praxissoftware'
languageCode = 'de-de'
title = 'Praxissoftware'
theme = 'hugo-book'

[params]
  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  BookSection = '*'

  BookSearch = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'
